# **ÖDEV-2**

1-Numpy kütüphanesini import edin.

In [3]:
import numpy as np

2-1'den 5 e kadar (5 dahil) b isimli bir dizi oluşturun.

In [11]:
array1 = np.arange(1,6)
array1

array([1, 2, 3, 4, 5])

3- 20 adet 0'dan oluşan 4 x 5' lik dizi oluşturun.

In [7]:
a = (4,5)
zero_matrix = np.zeros(a)
zero_matrix

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

4- 15 adet 7 sayısından oluşan diziyi 3x5 olarak yazın.

In [16]:
seven_matrix = np.full((3,5),7)
seven_matrix

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

5- 10–70 e kadar 5 er artan sayıları yaz.

In [17]:
ten_to_seventy = np.arange(10,70, 5)
ten_to_seventy

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65])

6- 10–20 arasında 15 aynı uzaklıkta elemanı olan array oluşturun. (linspace metodunu kullanın.)

In [18]:
ten_to_twenty = np.linspace(10,20,15)
ten_to_twenty

array([10.        , 10.71428571, 11.42857143, 12.14285714, 12.85714286,
       13.57142857, 14.28571429, 15.        , 15.71428571, 16.42857143,
       17.14285714, 17.85714286, 18.57142857, 19.28571429, 20.        ])

7- Rastgele sayılardan oluşan diziyi 3x5 boyutunda yazdır.

In [24]:
randarray = np.random.randint(100, size = 15)
randarray = randarray.reshape(3,5)
randarray

array([[34, 96, 46,  9, 68],
       [53, 53, 54, 34, 97],
       [68, 75, 28, 80, 51]])

8- 5 elemanlı birim matris oluşturun. eye() metodu kullanın.

In [25]:
unit_matrix = np.eye(5, dtype=int)
unit_matrix

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

9- 0'dan 24 e kadar array oluştur. Sonra reshape metodu ile 4x6 boyutu olarak yazın.

In [28]:
zero_to_24 = np.arange(24)
zero_to_24.reshape(4,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

10- 0 ile 1 arasında rastgele 10 sayıdan oluşan bir array tanımlayın. Minimum ve maksimum değerleri bulun.

In [41]:
randarray01 = np.random.randint(2, size = 10)
minvalue = randarray01.min()
maxvalue = randarray01.max()
print(minvalue,maxvalue)

0 1


11- 36 sayıdan oluşan rastgele sayılar 6x6' lık array olarak yazdırın.

In [33]:
randarray36 = np.random.randint(100, size = 36)
randarray36 = randarray36.reshape(6,6)
print(randarray36)

[[ 6 17 67 60 46 57]
 [71 14 79 17 75 92]
 [26 95 20 87 44 17]
 [50 36  7 64 35 51]
 [33  5 74 79 86 99]
 [27 32 62 10 81 45]]


12- 5.satırdaki elemanları gösteriniz.

In [37]:
randarray36[4]

array([33,  5, 74, 79, 86, 99])

13- 6.satır ve 6.sutundaki elemanları gösteriniz.

In [38]:
randarray36[5][5]

45

14-4.sutundaki tüm elemanları çekin.

In [39]:
new_array = randarray36[3]
new_array

array([50, 36,  7, 64, 35, 51])

15- For döngüsünü ve flat metodunu kullanarak satır satır elemanları yazdırınız.

In [40]:
for i in range(36):
    randarray36 = randarray36.reshape(1,36)
    print(randarray36.flat[i])

6
17
67
60
46
57
71
14
79
17
75
92
26
95
20
87
44
17
50
36
7
64
35
51
33
5
74
79
86
99
27
32
62
10
81
45


16- 0 ile 1 aralığında bir array oluştur. Bu array değerini 5 ile çarpın.

In [44]:
randarray01 = np.random.randint(2, size = 10)
randarray01_times = randarray01*5
randarray01_times

array([5, 5, 0, 0, 5, 5, 0, 0, 5, 5])

16- Satırların toplam değeri nedir?

In [45]:
randarray01_times.sum()

30

17-Satırların standart sapma değeri nedir?

In [47]:
randarray01_times.std()

2.449489742783178

18-Satırların varyans değeri nedir?

In [48]:
randarray01_times.var()

6.0

19- Satırların transpoz değeri nedir?

In [49]:
randarray01_times.T

array([5, 5, 0, 0, 5, 5, 0, 0, 5, 5])